-- Миграция: CRM Чаты — user_chat_messages, доработка user_message_delivery, RPC Messages
-- Выполнить в Supabase SQL Editor при необходимости.

-- 1) Таблица истории чатов (если ещё нет)
CREATE TABLE IF NOT EXISTS public.user_chat_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tg_user_id bigint NOT NULL,
  direction text NOT NULL CHECK (direction IN ('inbound', 'outbound')),
  message_text text NOT NULL DEFAULT '',
  source text,  -- 'manual' | 'bot' | 'user'
  delivery_id bigint REFERENCES public.user_message_delivery(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_user_chat_messages_tg_user_id ON public.user_chat_messages(tg_user_id);
CREATE INDEX IF NOT EXISTS idx_user_chat_messages_created_at ON public.user_chat_messages(created_at);

-- 2) Колонки в user_message_delivery для ручных сообщений (если ещё нет)
ALTER TABLE public.user_message_delivery
  ADD COLUMN IF NOT EXISTS is_manual boolean NOT NULL DEFAULT false;
ALTER TABLE public.user_message_delivery
  ADD COLUMN IF NOT EXISTS manual_text text;

-- 3) RPC: отправить сообщение от админа (добавляет в очередь и в историю чата)
CREATE OR REPLACE FUNCTION public."Messages"(p_tg_user_id bigint, p_text text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_delivery_id bigint;
  v_now timestamptz := now();
BEGIN
  INSERT INTO public.user_message_delivery (tg_user_id, message_id, is_manual, manual_text, status, scheduled_at)
  VALUES (p_tg_user_id, NULL, true, p_text, 'pending', v_now)
  RETURNING id INTO v_delivery_id;

  INSERT INTO public.user_chat_messages (tg_user_id, direction, message_text, source, delivery_id)
  VALUES (p_tg_user_id, 'outbound', p_text, 'manual', v_delivery_id);

  RETURN jsonb_build_object('delivery_id', v_delivery_id);
END;
$$;

-- 4) Realtime: в Supabase Dashboard → Database → Replication включите
--    публикацию для таблицы public.user_chat_messages.

-- Если в user_message_delivery используется user_id вместо tg_user_id:
-- ALTER TABLE public.user_message_delivery ADD COLUMN IF NOT EXISTS tg_user_id bigint;
-- UPDATE public.user_message_delivery SET tg_user_id = user_id WHERE tg_user_id IS NULL;
