-- Миграция: чат с экспертом — хранение переписки как в боте
-- Выполнить в Supabase SQL Editor при необходимости.

CREATE TABLE IF NOT EXISTS public.cabinet_expert_chat_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tg_user_id bigint,
  cookie_id text,
  direction text NOT NULL CHECK (direction IN ('inbound', 'outbound')),
  message_text text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_cabinet_expert_tg_user_id ON public.cabinet_expert_chat_messages(tg_user_id);
CREATE INDEX IF NOT EXISTS idx_cabinet_expert_cookie_id ON public.cabinet_expert_chat_messages(cookie_id);
CREATE INDEX IF NOT EXISTS idx_cabinet_expert_created_at ON public.cabinet_expert_chat_messages(created_at);

COMMENT ON TABLE public.cabinet_expert_chat_messages IS 'Переписка с Экспертом. inbound = сообщение пользователя, outbound = ответ ИИ.';

-- RLS: разрешить вставку и чтение для anon (мини-приложение) и authenticated
ALTER TABLE public.cabinet_expert_chat_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow insert for cabinet expert chat" ON public.cabinet_expert_chat_messages
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow select for cabinet expert chat" ON public.cabinet_expert_chat_messages
  FOR SELECT USING (true);
